---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: express
  namespace: default
spec:
  selector:
    matchLabels:
      app: express
  template:
    metadata:
      labels:
        app: express
    spec:
      containers:
        - name: express
          imagePullPolicy: Always
          image: aputrabay/express:latest
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: 200m # 200 millicpu = 0.2 cpu (core)
